# config_version=3

mode:
  priority: 100
# code: carousel_3.carousel_3
  start_events: carousel_3_selected
  stop_events: carousel_3_complete, carousel_3_failed

logic_blocks:
  sequences:
    carousel_3:
      events:
        - s_test_3_active
      events_when_complete: carousel_3_complete, carousel_mode_complete
