# config_version=3

mode:
  priority: 100
# code: stargazer.stargazer
  start_events: stargazer_selected
  stop_events: stargazer_complete, stargazer_failed

shot_profiles:
  hit_me:
    states:
      - name: active
        light_script: flash_magenta
      - name: complete
        light_script: on_magenta

shots:
  kick_out_left:
    profile: hit_me
    reset_events: mode_stargazer_stopping
  kick_out_right:
    profile: hit_me
    reset_events: mode_stargazer_stopping
  spinner:
    profile: hit_me
    reset_events: mode_stargazer_stopping
    enable_events: stargazer_kick_outs_complete

shot_groups:
  stargazer_kick_outs:
    shots: kick_out_left, kick_out_right
    enable_events: mode_stargazer_started
    reset_events: mode_stargazer_stopping

logic_blocks:
  accruals:
    thats_one:
      events:
        - kick_out_left_hit_me_active_hit, kick_out_right_hit_me_active_hit
      events_when_complete:
        play_thats_one

  sequences:
    stargazer_stage_1:
      events: 
        - kick_out_left_hit_me_active_hit, kick_out_right_hit_me_active_hit
      reset_events: mode_stargazer_stopping
    stargazer_stage_2:
      events:
        - logicblock_stargazer_stage_1_complete 
        - kick_out_left_hit_me_active_hit, kick_out_right_hit_me_active_hit
      reset_events: mode_stargazer_stopping
    stargazer:
      events:
        - logicblock_stargazer_stage_2_complete
        - spinner_hit_me_active_hit
      reset_events: mode_stargazer_stopping
      events_when_complete: stargazer_complete, carousel_mode_complete

light_player:
  logicblock_stargazer_stage_2_complete:
    - show: multiball_wave_magenta
      repeat: yes
  mode_stargazer_stopping:
    - show: multiball_wave_magenta
      action: stop

scoring:
  logicblock_stargazer_stage_1_complete:
    score: 10000

  logicblock_stargazer_stage_2_complete:
    score: 20000

  stargazer_complete:
    score: 120000
