# config_version=3

mode:
  priority: 100
  code: base.base
  start_events: ball_starting

ball_saves:
  default:
    active_time: 1s
    enable_events: balldevice_plunger_lane_ball_left
    balls_to_save: 1
    debug: yes
    auto_launch: no

timers:
  ball_save:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 0.5s
    control_events:
      - event: ball_save_default_enabled
        action: start

sound_player:
  lets go:
    sound: lets_go
    start_events: mode_base_started

  hey wait for me:
    sound: hey_wait_for_me
    start_events: balldevice_plunger_lane_ball_left

  gaming highlighted:
    sound: gaming_highlighted
    start_events: gaming_highlighted
    stop_events: gaming_unhighlighted

  vendor highlighted:
    sound: vendor_highlighted
    start_events: vendor_highlighted
    stop_events: vendor_unhighlighted

  auction highlighted:
    sound: auction_highlighted
    start_events: auction_highlighted
    stop_events: auction_unhighlighted

  photo highlighted:
    sound: photo_highlighted
    start_events: photo_highlighted
    stop_events: photo_unhighlighted

  cosplay highlighted:
    sound: cosplay_highlighted
    start_events: cosplay_highlighted
    stop_events: cosplay_unhighlighted

  stargazer highlighted:
    sound: stargazer_highlighted
    start_events: stargazer_highlighted
    stop_events: stargazer_unhighlighted

  gaming started:
    sound: gaming_started
    start_events: mode_gaming_started
  gaming stage 1:
    sound: bested_mcnabs
    start_events: logicblock_gaming_stage_1_complete
  gaming stage 2:
    sound: save_vs_con_crud
    start_events: logicblock_gaming_stage_2_complete
  gaming complete:
    sound: curses_foiled
    start_events: gaming_complete

  vendor started:
    sound: sale_action_figures
    start_events: mode_vendor_started
  vendor stage 1:
    sound: look_with_eyes
    start_events: logicblock_vendor_stage_1_complete
  vendor stage 2:
    sound: you_break_it
    start_events: logicblock_vendor_stage_2_complete
  vendor complete:
    sound: great_shooting
    start_events: vendor_complete

  auction started:
    sound: auction_started
    start_events: mode_auction_started
  auction bid 1:
    sound: chant-TEN-01
    start_events: auction_bid_1
  auction bid 2:
    sound: chant-TWENTY-02
    start_events: auction_bid_2
  auction bid 3:
    sound: chant-THIRTY-04
    start_events: auction_bid_3
  auction bid 4:
    sound: chant-FORTY-01
    start_events: auction_bid_4
  auction bid 5:
    sound: chant-FIFTY-01
    start_events: auction_bid_5
  auction bid 6:
    sound: chant-SIXTY-01
    start_events: auction_bid_6
  auction bid 7:
    sound: chant-SEVENTY-01
    start_events: auction_bid_7
  auction player wins:
    sound: auction_sold_credits
    start_events: logicblock_player_bid_complete
  auction player loses:
    sound: auction_sold_villain
    start_events: timer_opponent_bid_complete

  jackpot enabled:
    sound: jackpot_enabled
    start_events: jackpot_enabled

  jackpot:
    sound: jackpot
    start_events: award_jackpot

  wizard enabled:
    sound: wizard_enabled
    start_events: mode_wizard_started

  extra ball:
    sound: extra_ball_achieved
    start_events: extra_ball_awarded

  pop bumper left:
    sound: little metal
    start_events: pop_bumper_left_hit

  pop bumper right:
    sound: medium metal
    start_events: pop_bumper_right_hit

  pop bumper bottom:
    sound: big metal
    start_events: pop_bumper_bottom_hit

  lanes:
    sound: fail
    start_events: upper_lane_1_hit, upper_lane_2_hit, upper_lane_3_hit

  kickouts:
    sound: explosion
    start_events: balldevice_kick_out_left_ball_enter, balldevice_kick_out_right_ball_enter

  targets:
    sound: standup hit unlit
    start_events: drop_target_left_1_down, drop_target_left_2_down, drop_target_left_3_down, drop_target_centre_1_down, drop_target_centre_2_down, drop_target_centre_3_down, drop_target_right_1_down, drop_target_right_2_down, drop_target_right_3_down, fixed_target_hit

  slingshots:
    sound: tiny laser
    start_events: slingshot_left_hit, slingshot_right_hit, spinner_hit

  slingshots:
    sound: tiny laser
    start_events: spinner_hit

  outlanes:
    sound: bad_feeling
    start_events: outlane_left_hit, outlane_right_hit

  inlanes:
    sound: little swoosh
    start_events: inlane_left_hit, inlane_right_hit
    
  drain:
    sound: sad_trombone
    start_events: balldevice_drain_ball_enter

slide_player:
  mode_base_started:
    - type: text
      text: "%score%"
      number_grouping: true
      min_digits: 2
      v_pos: center
      transition:
        type: move_in
    - type: text
      text: PLAYER %number%
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: BALL %ball%
      v_pos: bottom
      h_pos: right
      font: small

  award_jackpot:
    - type: text
      text: "JACKPOT!!!"
      font: weltron
      size: 24
      expire: 3s

  extra_ball_awarded:
    - type: text
      text: "EXTRA BALL!"
      font: weltron
      size: 24
      expire: 5s


  mode_wizard_started:
    - type: text
      text: "WIZARD MODE!"
      font: weltron
      size: 24
      expire: 3s

light_player:
  carousel_select_restart_lock_enable:
    - show: kick_out_left_arrow_chase_rainbow
      repeat: yes
    - show: kick_out_right_arrow_chase_rainbow
      repeat: yes
  mode_carousel_select_starting:
    - show: kick_out_left_arrow_chase_rainbow
      action: stop
    - show: kick_out_right_arrow_chase_rainbow
      action: stop
  pop_bumper_left_hit:
    - show: pop_bumper_left_solid_white
  pop_bumper_right_hit:
    - show: pop_bumper_right_solid_white
  pop_bumper_bottom_hit:
    - show: pop_bumper_bottom_solid_white

scoring:
  upper_lane_1_hit:
    score: 100
    experience_points: 1

  upper_lane_2_hit:
    score: 100
    experience_points: 1

  upper_lane_3_hit:
    score: 100
    experience_points: 1

  pop_bumper_left_hit:
    score: 10

  pop_bumper_right_hit:
    score: 10

  pop_bumper_bottom_hit:
    score: 10

  drop_target_left_1_down:
    score: 100
  drop_target_left_2_down:
    score: 100
  drop_target_left_3_down:
    score: 100

  drop_target_right_1_down:
    score: 100
  drop_target_right_2_down:
    score: 100
  drop_target_right_3_down:
    score: 100

  drop_target_centre_1_down:
    score: 1000
  drop_target_centre_2_down:
    score: 1000
  drop_target_centre_2_down:
    score: 1000

  fixed_target_hit:
    score: 5000

  balldevice_kick_out_right_ball_enter:
    score: 1000
  balldevice_kick_out_left_ball_enter:
    score: 1000

  slingshot_left_hit:
    score: 10
  slingshot_right_hit:
    score: 10

  outlane_left_hit:
    score: 1000
  inlane_left_hit:
    score: 100
  inlane_right_hit:
    score: 100
  outlane_right_hit:
    score: 1000

  spinner_hit:
    score: 100

  main_stage_entry_hit:
    score: 1000
