# config_version=3

mode:
  priority: 100
  code: base.base
  start_events: ball_starting

ball_saves:
  default:
    active_time: 1s
    enable_events: balldevice_plunger_lane_ball_left
    balls_to_save: 1
    debug: yes
    auto_launch: no

timers:
  ball_save:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 0.5s
    control_events:
      - event: ball_save_default_enabled
        action: start

sound_player:
  lets go:
    sound: lets_go
    start_events: mode_base_started

  hey wait for me:
    sound: hey_wait_for_me
    start_events: balldevice_plunger_lane_ball_left

  gaming highlighted:
    sound: gaming_highlighted
    start_events: gaming_highlighted
    stop_events: gaming_unhighlighted

  vendor highlighted:
    sound: vendor_highlighted
    start_events: vendor_highlighted
    stop_events: vendor_unhighlighted

  auction highlighted:
    sound: auction_highlighted
    start_events: auction_highlighted
    stop_events: auction_unhighlighted

  photo highlighted:
    sound: photo_highlighted
    start_events: photo_highlighted
    stop_events: photo_unhighlighted

  cosplay highlighted:
    sound: cosplay_highlighted
    start_events: cosplay_highlighted
    stop_events: cosplay_unhighlighted

  stargazer highlighted:
    sound: stargazer_highlighted
    start_events: stargazer_highlighted
    stop_events: stargazer_unhighlighted

  jackpot enabled:
    sound: jackpot_enabled
    start_events: jackpot_enabled

  jackpot:
    sound: jackpot
    start_events: award_jackpot

  wizard enabled:
    sound: wizard_enabled
    start_events: mode_wizard_started

  extra ball:
    sound: extra_ball_achieved
    start_events: extra_ball_awarded

slide_player:
  mode_base_started:
    - type: text
      text: "%score%"
      number_grouping: true
      min_digits: 2
      v_pos: center
      transition:
        type: move_in
    - type: text
      text: PLAYER %number%
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: BALL %ball%
      v_pos: bottom
      h_pos: right
      font: small

  award_jackpot:
    - type: text
      text: "JACKPOT!!!"
      font: weltron
      size: 24
      expire: 3s

  extra_ball_awarded:
    - type: text
      text: "EXTRA BALL!"
      font: weltron
      size: 24
      expire: 5s


  mode_wizard_started:
    - type: text
      text: "WIZARD MODE!"
      font: weltron
      size: 24
      expire: 3s

scoring:
  upper_lane_1_hit:
    experience_points: 1

  upper_lane_2_hit:
    experience_points: 1

  upper_lane_3_hit:
    experience_points: 1
