# config_version=3

mode:
  priority: 100
  code: base.base
  start_events: ball_starting

ball_saves:
  default:
    active_time: 1s
    enable_events: balldevice_plungerLane_ball_eject_success
    balls_to_save: 1
    debug: yes
    auto_launch: no

timers:
  ball_save:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 0.5s
    control_events:
      - event: ball_save_default_enabled
        action: start

slide_player:
  mode_base_started:
    - type: text
      text: "%score%"
      number_grouping: true
      min_digits: 2
      v_pos: center
      transition:
        type: move_in
    - type: text
      text: PLAYER %number%
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: BALL %ball%
      v_pos: bottom
      h_pos: right
      font: small

  award_jackpot:
    - type: text
      text: "JACKPOT!!!"
      font: weltron
      size: 24
      expire: 3s

  extra_ball_awarded:
    - type: text
      text: "EXTRA BALL!"
      font: weltron
      size: 24
      expire: 5s


  mode_wizard_started:
    - type: text
      text: "WIZARD MODE!"
      font: weltron
      size: 24
      expire: 3s

scoring:
  upper_lane_1_hit:
    experience_points: 1

  upper_lane_2_hit:
    experience_points: 1

  upper_lane_3_hit:
    experience_points: 1