# config_version=3

mode:
  start_events: ball_starting, ball_lock_carousel_select_restart_lock_full
  stop_events: carousel_mode_selected
  priority: 200
  code: carousel_select.CarouselSelect

slide_player:
  gaming_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "GAMING FLOOR"
      color: ff0000
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

  vendor_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "VENDOR AREA"
      color: ffcc00
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

  auction_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "CHARITY AUCTION"
      color: ffff00
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

  photo_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "PHOTO OPS"
      color: 00ff00
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

  cosplay_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "COSPLAY CONTEST"
      color: 0000ff
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

  stargazer_highlighted:
    - type: text
      text: CHOOSE YOUR MODE
      v_pos: top
      font: small
    - type: text
      text: "STARGAZER SOIREE"
      color: ff00ff
    - type: text
      text: << SELECT
      v_pos: bottom
      h_pos: left
      font: small
    - type: text
      text: NEXT >>
      v_pos: bottom
      h_pos: right
      font: small

light_player:
  gaming_highlighted:
    - show: gaming_mode_wave_red
      repeat: yes
    - show: drop_target_left_wave_red
      repeat: yes
    - show: kick_out_left_arrow_wave_red
      repeat: yes
    - show: kick_out_right_arrow_wave_red
      repeat: yes
  gaming_unhighlighted:
    - show: gaming_mode_wave_red
      action: stop
    - show: drop_target_left_wave_red
      action: stop
    - show: kick_out_left_arrow_wave_red
      action: stop
    - show: kick_out_right_arrow_wave_red
      action: stop

  vendor_highlighted:
    - show: vendor_mode_wave_orange
      repeat: yes
    - show: pop_bumper_left_wave_orange
      repeat: yes
    - show: pop_bumper_right_wave_orange
      repeat: yes
    - show: pop_bumper_bottom_wave_orange
      repeat: yes
  vendor_unhighlighted:
    - show: vendor_mode_wave_orange
      action: stop
    - show: pop_bumper_left_wave_orange
      action: stop
    - show: pop_bumper_right_wave_orange
      action: stop
    - show: pop_bumper_bottom_wave_orange
      action: stop

  auction_highlighted:
    - show: auction_mode_wave_yellow
      repeat: yes
    - show: spinner_arrow_wave_yellow
      repeat: yes
    - show: player_bid_wave_yellow
      repeat: yes
    - show: opponent_bid_wave_yellow
      repeat: yes
  auction_unhighlighted:
    - show: auction_mode_wave_yellow
      action: stop
    - show: spinner_arrow_wave_yellow
      action: stop
    - show: player_bid_wave_yellow
      action: stop
    - show: opponent_bid_wave_yellow
      action: stop

  photo_highlighted:
    - show: photo_mode_wave_green
      repeat: yes
    - show: drop_target_centre_arrow_wave_green
      repeat: yes
  photo_unhighlighted:
    - show: photo_mode_wave_green
      action: stop
    - show: drop_target_centre_arrow_wave_green
      action: stop

  cosplay_highlighted:
    - show: cosplay_mode_wave_blue
      repeat: yes
    - show: main_stage_wave_blue
      repeat: yes
    - show: drop_target_right_wave_blue
      repeat: yes
  cosplay_unhighlighted:
    - show: cosplay_mode_wave_blue
      action: stop
    - show: main_stage_wave_blue
      action: stop
    - show: drop_target_right_wave_blue
      action: stop

  stargazer_highlighted:
    - show: stargazer_mode_wave_magenta
      repeat: yes
    - show: kick_out_left_arrow_wave_magenta
      repeat: yes
    - show: kick_out_right_arrow_wave_magenta
      repeat: yes
    - show: spinner_arrow_wave_magenta
      repeat: yes
    - show: multiball_wave_magenta
      repeat: yes
  stargazer_unhighlighted:
    - show: stargazer_mode_wave_magenta
      action: stop
    - show: kick_out_left_arrow_wave_magenta
      action: stop
    - show: kick_out_right_arrow_wave_magenta
      action: stop
    - show: spinner_arrow_wave_magenta
      action: stop
    - show: multiball_wave_magenta
      action: stop
