#config_version=3

mode:
  start_events: ball_ending
  stop_events: timer_bonus_complete
  priority: 500
  use_wait_queue: true

slide_player:
  mode_bonus_started:
    type: text
    text: BONUS

timers:
  bonus:
    start_value: 3
    start_running: true
    direction: down