#config_version=3

mode:
  start_events: ball_ending
  stop_events: timer_mode_cooldown_complete
  priority: 500
  use_wait_queue: true
  code: bonus.Bonus

slide_player:
  mode_bonus_started:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 0
      h_pos: left
      persist_slide: true
    - type: text
      text: "%counted_experience_points_value%"
      number_grouping: true 
      font: small
      y: 0
      h_pos: right

  count_experience_points_complete:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 0
      h_pos: left
      persist_slide: true
    - type: text
      text: "%counted_experience_points_value%"
      number_grouping: true 
      font: small
      y: 0
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 6
      h_pos: left
    - type: text
      text: "x%experience_point_multiplier%"
      font: small
      y: 6
      h_pos: right

  timer_update_bonus_complete:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 0
      h_pos: left
      persist_slide: true
    - type: text
      text: "%counted_experience_points_value%"
      number_grouping: true 
      font: small
      y: 0
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 6
      h_pos: left
    - type: text
      text: "x%experience_point_multiplier%"
      font: small
      y: 6
      h_pos: right

    - type: text
      text: "Total Bonus:"
      font: small
      y: 12
      h_pos: left
    - type: text
      text: "%jackpot_value%"
      number_grouping: true 
      font: small
      y: 12
      h_pos: right

  timer_update_previous_score_complete:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 0
      h_pos: left
      persist_slide: true
    - type: text
      text: "%counted_experience_points_value%"
      number_grouping: true 
      font: small
      y: 0
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 6
      h_pos: left
    - type: text
      text: "x%experience_point_multiplier%"
      font: small
      y: 6
      h_pos: right

    - type: text
      text: "Total Bonus:"
      font: small
      y: 12
      h_pos: left
    - type: text
      text: "%jackpot_value%"
      number_grouping: true 
      font: small
      y: 12
      h_pos: right

    - type: text
      text: "Score:"
      font: small
      y: 18
      h_pos: left
    - type: text
      text: "%previous_score%"
      number_grouping: true 
      font: small
      y: 18
      h_pos: right

  timer_update_final_score_complete:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 0
      h_pos: left
      persist_slide: true
    - type: text
      text: "%counted_experience_points_value%"
      number_grouping: true 
      font: small
      y: 0
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 6
      h_pos: left
    - type: text
      text: "x%experience_point_multiplier%"
      font: small
      y: 6
      h_pos: right

    - type: text
      text: "Total Bonus:"
      font: small
      y: 12
      h_pos: left
    - type: text
      text: "%jackpot_value%"
      number_grouping: true 
      font: small
      y: 12
      h_pos: right

    - type: text
      text: "Score:"
      font: small
      y: 18
      h_pos: left
    - type: text
      text: "%previous_score%"
      number_grouping: true 
      font: small
      y: 18
      h_pos: right

    - type: shape
      shape: box
      y: 24
      width: 128
      height: 1

    - type: text
      text: "Total:"
      font: small
      y: 26
      h_pos: left
    - type: text
      text: "%score%"
      number_grouping: true 
      font: small
      y: 26
      h_pos: right

timers:
  update_bonus:
    end_value: 2
    control_events:
      - event: count_experience_points_complete
        action: start

  update_previous_score:
    end_value: 2
    control_events:
      - event: timer_update_bonus_complete
        action: start

  update_final_score:
    end_value: 2
    control_events:
      - event: timer_update_previous_score_complete
        action: start

  mode_cooldown:
    end_value: 2
    control_events:
      - event: timer_update_final_score_complete
        action: start