#config_version=3

mode:
  start_events: ball_ending
  stop_events: timer_mode_cooldown_complete
  priority: 500
  use_wait_queue: true
  code: bonus.Bonus

slide_player:
  bonus_update_experience_points:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 1
      x: 4
      persist_slide: true
    - type: text
      text: "%player|counted_experience_points%"
      number_grouping: true 
      font: small
      y: 1
      h_pos: right

  bonus_update_multiplier:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 1
      x: 4
      persist_slide: true
    - type: text
      text: "%player|counted_experience_points%"
      number_grouping: true 
      font: small
      y: 1
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 8
      x: 6
    - type: text
      text: "x%player|counted_multiplier%"
      font: small
      y: 8
      h_pos: right

  bonus_update_bonus:
    - type: text
      text: "Exp. Points:"
      font: small
      y: 1
      x: 4
      persist_slide: true
    - type: text
      text: "%player|counted_experience_points%"
      number_grouping: true 
      font: small
      y: 1
      h_pos: right

    - type: text
      text: "Multiplier:"
      font: small
      y: 8
      x: 6
    - type: text
      text: "x%player|counted_multiplier%"
      font: small
      y: 8
      h_pos: right

    - type: text
      text: "Total Bonus:"
      font: small
      y: 15
      x: 1
    - type: text
      text: "%player|counted_bonus%"
      number_grouping: true 
      font: small
      y: 15
      h_pos: right

timers:
  mode_cooldown:
    end_value: 3
    control_events:
      - event: bonus_update_bonus
        action: start