# config_version=3

mode:
  start_events: carousel_1_selected
  stop_events: carousel_1_complete, carousel_1_failed
  priority: 100

logic_blocks:
  sequences:
    carousel_1:
      events:
        - s_test_3_active
      events_when_complete: carousel_1_complete, carousel_mode_complete