# config_version=3

mode:
  priority: 100
# code: carousel_1.carousel_1
  start_events: carousel_1_selected
  stop_events: carousel_1_complete, carousel_1_failed

logic_blocks:
  sequences:
    carousel_1:
      events:
        - s_test_3_active
      events_when_complete: carousel_1_complete, carousel_mode_complete
