# config_version=3

mode:
  priority: 100
  code: auction.auction
  start_events: auction_selected
  stop_events: auction_complete, auction_failed

shot_profiles:
  hit_me:
    states:
      - name: active
        light_script: flash_yellow
      - name: complete
        light_script: on_yellow

shots:
  auction_collect:
    switch: s_main_stage_entry
    led:
      - l_main_stage_arrow_1_a
      - l_main_stage_arrow_1_b
      - l_main_stage_arrow_1_c
      - l_main_stage_arrow_1_d
      - l_main_stage_arrow_1_e
      - l_main_stage_arrow_1_f
      - l_main_stage_arrow_1_g
      - l_main_stage_arrow_1_h
      - l_main_stage_arrow_2_a
      - l_main_stage_arrow_2_b
      - l_main_stage_arrow_2_c
      - l_main_stage_arrow_2_d
      - l_main_stage_arrow_2_e
      - l_main_stage_arrow_2_f
      - l_main_stage_arrow_2_g
      - l_main_stage_arrow_2_h
      - l_main_stage_arrow_3_a
      - l_main_stage_arrow_3_b
      - l_main_stage_arrow_3_c
      - l_main_stage_arrow_3_d
      - l_main_stage_arrow_3_e
      - l_main_stage_arrow_3_f
      - l_main_stage_arrow_3_g
      - l_main_stage_arrow_3_h
      - l_main_stage_edge_a
      - l_main_stage_edge_b
      - l_main_stage_edge_c
      - l_main_stage_edge_d
      - l_main_stage_edge_e
      - l_main_stage_edge_f
      - l_main_stage_edge_g
      - l_main_stage_edge_h
      - l_main_stage_edge_i
      - l_main_stage_edge_j
      - l_main_stage_edge_k
      - l_main_stage_edge_l
      - l_main_stage_edge_m
    profile: hit_me
    enable_events: logicblock_player_bid_complete
    reset_events: mode_auction_stopping

logic_blocks:
  counters:
    player_bid:
      count_events: spinner_hit
      count_complete_value: 80
      direction: up
      reset_events: mode_auction_stopping

  sequences:
    auction:
      events: auction_collect_hit_me_active_hit
      reset_events: mode_auction_stopping
      events_when_complete: auction_complete, carousel_mode_complete

timers:
  opponent_bid:
    end_value: 160
    control_events:
      - event: mode_auction_started
        action: start
      - event: logicblock_player_bid_complete
        action: stop

event_player:
  timer_opponent_bid_complete:
    auction_failed

scoring:
  spinner_hit:
    score: 250

  logicblock_player_bid_complete:
    score: 30000

  auction_complete:
    score: 100000
