# config_version=3

mode:
  priority: 100
# code: cosplay.cosplay
  start_events: cosplay_selected
  stop_events: cosplay_complete, cosplay_failed

light_player:
  mode_cosplay_started:
    - show: cosplay_mode_wave_blue
      repeat: yes
  mode_cosplay_stopping:
    - show: cosplay_mode_wave_blue
      action: stop

shot_profiles:
  hit_me:
    states:
      - name: active
        light_script: flash_blue
      - name: complete
        light_script: on_blue

shots:
  drop_target_right_1:
    profile: hit_me
    reset_events: mode_cosplay_stopping
  drop_target_right_2:
    profile: hit_me
    reset_events: mode_cosplay_stopping
  drop_target_right_3:
    profile: hit_me
    reset_events: mode_cosplay_stopping
  main_stage_entry_1:
    switch: s_main_stage_entry
    led:
      - l_main_stage_arrow_1_a
      - l_main_stage_arrow_1_b
      - l_main_stage_arrow_1_c
      - l_main_stage_arrow_1_d
      - l_main_stage_arrow_1_e
      - l_main_stage_arrow_1_f
      - l_main_stage_arrow_1_g
      - l_main_stage_arrow_1_h
      - l_main_stage_edge_a
      - l_main_stage_edge_b
      - l_main_stage_edge_c
      - l_main_stage_edge_d
      - l_main_stage_edge_e
      - l_main_stage_edge_f
      - l_main_stage_edge_g
      - l_main_stage_edge_h
      - l_main_stage_edge_i
      - l_main_stage_edge_j
      - l_main_stage_edge_k
      - l_main_stage_edge_l
      - l_main_stage_edge_m
    profile: hit_me
    enable_events: drop_target_bank_right_down
    reset_events: mode_cosplay_stopping
  main_stage_entry_2:
    switch: s_main_stage_entry
    led:
      - l_main_stage_arrow_2_a
      - l_main_stage_arrow_2_b
      - l_main_stage_arrow_2_c
      - l_main_stage_arrow_2_d
      - l_main_stage_arrow_2_e
      - l_main_stage_arrow_2_f
      - l_main_stage_arrow_2_g
      - l_main_stage_arrow_2_h
      - l_main_stage_edge_a
      - l_main_stage_edge_b
      - l_main_stage_edge_c
      - l_main_stage_edge_d
      - l_main_stage_edge_e
      - l_main_stage_edge_f
      - l_main_stage_edge_g
      - l_main_stage_edge_h
      - l_main_stage_edge_i
      - l_main_stage_edge_j
      - l_main_stage_edge_k
      - l_main_stage_edge_l
      - l_main_stage_edge_m
    profile: hit_me
    enable_events: main_stage_entry_1_hit_me_active_hit
    reset_events: mode_cosplay_stopping
  main_stage_entry_3:
    switch: s_main_stage_entry
    led:
      - l_main_stage_arrow_3_a
      - l_main_stage_arrow_3_b
      - l_main_stage_arrow_3_c
      - l_main_stage_arrow_3_d
      - l_main_stage_arrow_3_e
      - l_main_stage_arrow_3_f
      - l_main_stage_arrow_3_g
      - l_main_stage_arrow_3_h
      - l_main_stage_edge_a
      - l_main_stage_edge_b
      - l_main_stage_edge_c
      - l_main_stage_edge_d
      - l_main_stage_edge_e
      - l_main_stage_edge_f
      - l_main_stage_edge_g
      - l_main_stage_edge_h
      - l_main_stage_edge_i
      - l_main_stage_edge_j
      - l_main_stage_edge_k
      - l_main_stage_edge_l
      - l_main_stage_edge_m
    profile: hit_me
    enable_events: main_stage_entry_2_hit_me_active_hit
    reset_events: mode_cosplay_stopping

shot_groups:
  drop_target_bank_right:
    shots: drop_target_right_1, drop_target_right_2, drop_target_right_3
    reset_events: ball_ended

logic_blocks:
  sequences:
    cosplay_stage_1:
      events:
        - drop_target_bank_right_down
      reset_events: mode_cosplay_stopping
    cosplay_stage_2:
      events:
        - logicblock_cosplay_stage_1_complete
        - main_stage_entry_1_hit_me_active_hit
      reset_events: mode_cosplay_stopping
    cosplay_stage_3:
      events:
        - logicblock_cosplay_stage_2_complete
        - main_stage_entry_2_hit_me_active_hit
      reset_events: mode_cosplay_stopping
    cosplay:
      events:
        - logicblock_cosplay_stage_3_complete
        - main_stage_entry_3_hit_me_active_hit
      reset_events: mode_cosplay_stopping
      events_when_complete: cosplay_complete, carousel_mode_complete


scoring:
  logicblock_cosplay_stage_1_complete:
    score: 10000

  logicblock_cosplay_stage_2_complete:
    score: 15000

  logicblock_cosplay_stage_3_complete:
    score: 25000

  cosplay_complete:
    score: 100000
