# config_version=3

mode:
  priority: 100
# code: cosplay.cosplay
  start_events: cosplay_selected
  stop_events: cosplay_complete, cosplay_failed

logic_blocks:
  sequences:
    cosplay:
      events:
        - s_test_3_active
      events_when_complete: cosplay_complete, carousel_mode_complete
