# config_version=3

mode:
  priority: 100
# code: carousel_2.carousel_2
  start_events: carousel_2_selected
  stop_events: carousel_2_complete, carousel_2_failed

logic_blocks:
  sequences:
    carousel_2:
      events:
        - s_test_3_active
      events_when_complete: carousel_2_complete, carousel_mode_complete
