#config_version=3

coils:
  c_drain_eject:
    pulse_ms: 9
    number: 5-3

  c_trough_eject:
    pulse_ms: 6
    number: 5-2

  c_flipper_right:
    number: 21-1

  c_flipper_left:
    number: 21-2

  c_pop_bumper_bottom:
    pulse_ms: 8
    number: 10-0

  c_pop_bumper_left:
    pulse_ms: 8
    number: 10-1

  c_pop_bumper_right:
    pulse_ms: 8
    number: 10-2

  c_drop_target_left_reset:
    pulse_ms: 10
    number: 1-2

  c_kick_out_left_eject:
    pulse_ms: 5
    number: 1-0

  c_slingshot_right:
    pulse_ms: 5
    number: 5-1

  c_slingshot_left:
    pulse_ms: 5
    number: 5-0

  c_kick_out_right_eject:
    pulse_ms: 5
    number: 1-1

  c_drop_target_right_reset:
    pulse_ms: 10
    number: 1-3

  c_drop_target_centre_reset:
    pulse_ms: 40
    number: 1-4
