#config_version=3

config:
  - switches.yaml
  - coils.yaml
  - devices.yaml
  - modes.yaml
  - dmd.yaml

fonts:
  weltron:
    file: WELTRON2.TTF

logic_blocks:
  counters:
    carousel_modes_completed:
      enable_events: ball_starting
      count_events: carousel_1_complete, carousel_2_complete, carousel_3_complete
      event_when_hit: jackpot_enabled
      count_complete_value: 2
      reset_events: mode_wizard_started
      disable_on_complete: true
  accruals:
    wizard_mode:
      enable_events: ball_starting
      events:
        - carousel_1_complete,
        - carousel_2_complete,
        - carousel_3_complete,
      events_when_complete: wizard_enabled
      reset_events: mode_wizard_started
      disable_on_complete: true

scriptlets:
    carousel_mode_complete_handler.CarouselModeCompleteHandler
