#config_version=3

config:
  - hardware.yaml
  - switches.yaml
  - coils.yaml
  - devices.yaml
  - modes.yaml
  - dmd.yaml
  - lights.yaml
  - light_scripts.yaml
  - targets.yaml
  - shots.yaml

fonts:
  weltron:
    file: WELTRON2.TTF

logic_blocks:
  counters:
    carousel_modes_completed:
      enable_events: ball_starting
      count_events: gaming_complete, vendor_complete, auction_complete, photo_complete, cosplay_complete, stargazer_complete
      event_when_hit: jackpot_enabled
      count_complete_value: 5
      reset_events: mode_wizard_started
      disable_on_complete: true

    jackpots_stopped:
      enable_events: ball_starting
      count_events: mode_jackpot_stopped
      event_when_hit: carousel_select_restart_lock_enable
      count_complete_value: 5
      reset_events: mode_wizard_stopped
      disable_on_complete: true

  accruals:
    wizard_mode:
      enable_events: ball_starting
      events:
        - gaming_complete,
        - vendor_complete,
        - auction_complete,
        - photo_complete,
        - cosplay_complete,
        - stargazer_complete,
      events_when_complete: wizard_enabled
      reset_events: mode_wizard_started
      disable_on_complete: true

scriptlets:
  carousel_mode_complete_handler.CarouselModeCompleteHandler
  player_experience_points_handler.PlayerExperiencePointsHandler
