# config_version=3

shots:
  kick_out_left:
    switch: s_kick_out_left
    led:
      - l_kick_out_left_arrow_a
      - l_kick_out_left_arrow_b
      - l_kick_out_left_arrow_c
      - l_kick_out_left_arrow_d
      - l_kick_out_left_arrow_e
      - l_kick_out_left_arrow_f
      - l_kick_out_left_arrow_g
      - l_kick_out_left_arrow_h
  kick_out_right:
    switch: s_kick_out_right
    led:
      - l_kick_out_right_arrow_a
      - l_kick_out_right_arrow_b
      - l_kick_out_right_arrow_c
      - l_kick_out_right_arrow_d
      - l_kick_out_right_arrow_e
      - l_kick_out_right_arrow_f
      - l_kick_out_right_arrow_g
      - l_kick_out_right_arrow_h

  spinner:
    switch: s_spinner
    led:
      - l_spinner_arrow_a
      - l_spinner_arrow_b
      - l_spinner_arrow_c
      - l_spinner_arrow_d
      - l_spinner_arrow_e
      - l_spinner_arrow_f
      - l_spinner_arrow_g
      - l_spinner_arrow_h

  upper_lane_1:
    switch: s_upper_lane_1
    led: l_upper_lane_1
  upper_lane_2:
    switch: s_upper_lane_2
    led: l_upper_lane_2
  upper_lane_3:
    switch: s_upper_lane_3
    led: l_upper_lane_3

shot_groups:
  upper_lanes:
    shots: upper_lane_1, upper_lane_2, upper_lane_3
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      upper_lanes_default_lit_complete

light_player:
  upper_lanes_default_lit_complete:
    show: upper_lane_chase_blue
    tocks_per_sec: 8
    repeat: yes
    num_repeats: 10
    priority: 1