# config_version=3

shots:
  pop_bumper_left:
    switch: s_pop_bumper_left

  pop_bumper_right:
    switch: s_pop_bumper_right

  pop_bumper_bottom:
    switch: s_pop_bumper_bottom

  kick_out_left:
    switch: s_kick_out_left
    led:
      - l_kick_out_left_arrow_a
      - l_kick_out_left_arrow_b
      - l_kick_out_left_arrow_c
      - l_kick_out_left_arrow_d
      - l_kick_out_left_arrow_e
      - l_kick_out_left_arrow_f
      - l_kick_out_left_arrow_g
      - l_kick_out_left_arrow_h
  kick_out_right:
    switch: s_kick_out_right
    led:
      - l_kick_out_right_arrow_a
      - l_kick_out_right_arrow_b
      - l_kick_out_right_arrow_c
      - l_kick_out_right_arrow_d
      - l_kick_out_right_arrow_e
      - l_kick_out_right_arrow_f
      - l_kick_out_right_arrow_g
      - l_kick_out_right_arrow_h

  spinner:
    switch: s_spinner
    led:
      - l_spinner_arrow_a
      - l_spinner_arrow_b
      - l_spinner_arrow_c
      - l_spinner_arrow_d
      - l_spinner_arrow_e
      - l_spinner_arrow_f
      - l_spinner_arrow_g
      - l_spinner_arrow_h

  upper_lane_1:
    switch: s_upper_lane_1
    led: l_upper_lane_1
  upper_lane_2:
    switch: s_upper_lane_2
    led: l_upper_lane_2
  upper_lane_3:
    switch: s_upper_lane_3
    led: l_upper_lane_3

  outlane_right:
    switch: s_outlane_right
    led: l_outlane_right_a, l_outlane_right_b, l_outlane_right_c
  inlane_right:
    switch: s_inlane_right
    led: l_inlane_right_a, l_inlane_right_b, l_inlane_right_c

  outlane_left:
    switch: s_outlane_left
    led: l_outlane_left_a, l_outlane_left_b, l_outlane_left_c
  inlane_left:
    switch: s_inlane_left
    led: l_inlane_left_a, l_inlane_left_b, l_inlane_left_c

  drop_target_left_1:
    switch: s_drop_target_left_1
    led: l_drop_target_left_1
  drop_target_left_2:
    switch: s_drop_target_left_2
    led: l_drop_target_left_2
  drop_target_left_3:
    switch: s_drop_target_left_3
    led: l_drop_target_left_3

  drop_target_centre_1:
    switch: s_drop_target_centre_1
    led:
      l_drop_target_centre_arrow_a
      l_drop_target_centre_arrow_b
      l_drop_target_centre_arrow_c
      l_drop_target_centre_arrow_d
      l_drop_target_centre_arrow_e
      l_drop_target_centre_arrow_f
      l_drop_target_centre_arrow_g
      l_drop_target_centre_arrow_h
  drop_target_centre_2:
    switch: s_drop_target_centre_2
    led:
      l_drop_target_centre_arrow_a
      l_drop_target_centre_arrow_b
      l_drop_target_centre_arrow_c
      l_drop_target_centre_arrow_d
      l_drop_target_centre_arrow_e
      l_drop_target_centre_arrow_f
      l_drop_target_centre_arrow_g
      l_drop_target_centre_arrow_h
  drop_target_centre_3:
    switch: s_drop_target_centre_3
    led:
      l_drop_target_centre_arrow_a
      l_drop_target_centre_arrow_b
      l_drop_target_centre_arrow_c
      l_drop_target_centre_arrow_d
      l_drop_target_centre_arrow_e
      l_drop_target_centre_arrow_f
      l_drop_target_centre_arrow_g
      l_drop_target_centre_arrow_h

  drop_target_right_1:
    switch: s_drop_target_right_1
    led: l_drop_target_right_1
  drop_target_right_2:
    switch: s_drop_target_right_2
    led: l_drop_target_right_2
  drop_target_right_3:
    switch: s_drop_target_right_3
    led: l_drop_target_right_3

  fixed_target:
    switch: s_fixed_target
    led:
      l_drop_target_centre_arrow_a
      l_drop_target_centre_arrow_b
      l_drop_target_centre_arrow_c
      l_drop_target_centre_arrow_d
      l_drop_target_centre_arrow_e
      l_drop_target_centre_arrow_f
      l_drop_target_centre_arrow_g
      l_drop_target_centre_arrow_h

  slingshot_left:
    switch: s_slingshot_left
  slingshot_right:
    switch: s_slingshot_right

  main_stage_entry:
    switch: s_main_stage_entry

shot_groups:
  upper_lanes:
    shots: upper_lane_1, upper_lane_2, upper_lane_3
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      upper_lanes_default_lit_complete

  lower_lanes:
    shots: outlane_left, inlane_left, inlane_right, outlane_right
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active
    reset_events:
      lower_lanes_default_lit_complete: 1s

  drop_target_bank_left:
    shots: drop_target_left_1, drop_target_left_2, drop_target_left_3
    reset_events:
      drop_target_bank_left_default_lit_complete

  drop_target_bank_right:
    shots: drop_target_right_1, drop_target_right_2, drop_target_right_3
    reset_events:
      drop_target_bank_right_default_lit_complete

light_player:
  upper_lanes_default_lit_complete:
    show: upper_lane_chase_blue
    tocks_per_sec: 8
    repeat: yes
    num_repeats: 10
    priority: 1

  drop_target_bank_left_default_lit_complete:
    show: drop_target_left_chase_blue
    tocks_per_sec: 8
    repeat: yes
    num_repeats: 10
    priority: 1

  drop_target_bank_right_default_lit_complete:
    show: drop_target_right_chase_blue
    tocks_per_sec: 8
    repeat: yes
    num_repeats: 10
    priority: 1
