#config_version=3

keyboard:
  s:
    switch: s_start

  d:
    switch: s_drain

  w:
    switch: s_tilt

  l:
    switch: s_slam_tilt

  1:
    switch: s_test_1

  2:
    switch: s_test_2

  3:
    switch: s_test_3

  4:
    switch: s_test_4

  5:
    switch: s_test_5

  6:
    switch: s_test_6

switches:
  s_drain:
    number: 5-0

  s_trough_1:
    number: 5-1

  s_trough_2:
    number: 5-2

  s_trough_3:
    number: 5-3

  s_start:
    number: 21-1
    tags: start

  s_flipper_left:
    number: 21-2
    tags: left_flipper, carousel_select_item

  s_flipper_right:
    number: 21-0
    tags: right_flipper, carousel_next_item

  s_wizard_cheat:
    number: 21-3
    tags: yer_a_wizard_harry

  s_outlane_right:
    number: 5-6

  s_inlane_right:
    number: 5-7

  s_inlane_left:
    number: 5-8

  s_outlane_left:
    number: 5-9

  s_plunger_lane:
    number: 5-4

  s_drop_target_left_3:
    number: 1-7

  s_drop_target_left_2:
    number: 1-6

  s_drop_target_left_1:
    number: 1-5

  s_upper_lane_1:
    number: 10-7

  s_upper_lane_2:
    number: 10-8

  s_upper_lane_3:
    number: 10-9

  s_spinner:
    number: 10-0
    debounce_open: 5
    debounce_close: 5

  s_rubber_switch_bottom:
    number: 10-6

  s_kick_out_left:
    number: 1-4

  s_pop_bumper_left:
    number: 10-2

  s_pop_bumper_bottom:
    number: 10-1

  s_pop_bumper_right:
    number: 10-3

  s_slingshot_right:
    number: 5-10
    
  s_slingshot_left:
    number: 5-11
    
  s_kick_out_right:
    number: 1-0
    
  s_drop_target_right_1:
    number: 1-1
    
  s_drop_target_right_2:
    number: 1-2
    
  s_drop_target_right_3:
    number: 1-3
    
  s_drop_target_centre_1:
    number: 1-8
    
  s_drop_target_centre_2:
    number: 1-9
    
  s_drop_target_centre_3:
    number: 1-10
    
  s_rubber_switch_side:
    number: 10-5
    
  s_fixed_target:
    number: 1-11
    
  s_main_stage_entry:
    number: 10-11
    tags: kingpyn_disable_pullup

  s_tilt:
    number: 21-4
    tags: tilt_warning

  s_slam_tilt:
    number: 21-5
    tags: slam_tilt

  s_test_1:
    number: 21-6
    tags: carousel_select_item

  s_test_2:
    number: 21-7
    tags: carousel_next_item

  s_test_3:
    number: 21-8

  s_test_4:
    number: 21-9

  s_test_5:
    number: 21-10

  s_test_6:
    number: 21-11
