#config_version=3

drop_targets:
  drop_target_left_1:
    switch: s_drop_target_left_1

  drop_target_left_2:
    switch: s_drop_target_left_2

  drop_target_left_3:
    switch: s_drop_target_left_3

  drop_target_right_1:
    switch: s_drop_target_right_1

  drop_target_right_2:
    switch: s_drop_target_right_2

  drop_target_right_3:
    switch: s_drop_target_right_3

  drop_target_centre_1:
    switch: s_drop_target_centre_1

  drop_target_centre_2:
    switch: s_drop_target_centre_2

  drop_target_centre_3:
    switch: s_drop_target_centre_3
  
drop_target_banks:
  drop_target_bank_left:
    drop_targets: drop_target_left_1, drop_target_left_2, drop_target_left_3
    reset_coils: c_drop_target_left_reset
    reset_events:
      ball_starting: 0
      mode_gaming_started: 0
      drop_target_bank_left_down: 1s

  drop_target_bank_right:
    drop_targets: drop_target_right_1, drop_target_right_2, drop_target_right_3
    reset_coils: c_drop_target_right_reset
    reset_events:
      ball_starting: 0
      mode_cosplay_started: 0
      drop_target_bank_right_down: 1s

  drop_target_bank_centre:
    drop_targets: drop_target_centre_1, drop_target_centre_2, drop_target_centre_3
    reset_coils: c_drop_target_centre_reset
    reset_events:
      ball_starting: 0
      mode_photo_started: 0
