# config_version=3

mode:
  priority: 100
# code: gaming.gaming
  start_events: gaming_selected
  stop_events: gaming_complete, gaming_failed

shot_profiles:
  hit_me:
    states:
      - name: active
        light_script: flash_green
      - name: complete
        light_script: on_green

shots:
  drop_target_left_1:
    profile: hit_me
    reset_events: mode_gaming_stopping
  drop_target_left_2:
    profile: hit_me
    reset_events: mode_gaming_stopping
  drop_target_left_3:
    profile: hit_me
    reset_events: mode_gaming_stopping
  kick_out_left:
    profile: hit_me
    enable_events: drop_target_bank_left_down
    reset_events: mode_gaming_stopping
  kick_out_right:
    profile: hit_me
    enable_events: drop_target_bank_left_down
    reset_events: mode_gaming_stopping

shot_groups:
  drop_target_bank_left:
    shots: drop_target_left_1, drop_target_left_2, drop_target_left_3

logic_blocks:
  accruals:
    gaming:
      events:
        - kick_out_left_hit
        - kick_out_right_hit
      enable_events: drop_target_bank_left_down
      reset_events: mode_gaming_stopping
      events_when_complete: gaming_complete, carousel_mode_complete

slide_player:
  gaming_selected:
    - type: text
      text: "GAMING BOTS!"
      expire: 3s
  drop_target_bank_left_down:
    - type: text
      text: "ROLL THE DICE!"
      expire: 3s

sound_player:
  bested my gaming bots:
    sound: bested_mcnabs
    start_events: drop_target_bank_left_down
  first roll:
    sound: save_vs_con_crud
    start_events: kick_out_left_hit
  second roll:
    sound: curses_foiled
    start_events: kick_out_right_hit

scoring:
  drop_target_bank_left_down:
    score: 10000

  kick_out_left_hit:
    score: 20000

  kick_out_right_hit:
    score: 20000

  gaming_complete:
    score: 100000
