# config_version=3

mode:
  priority: 100
# code: gaming.gaming
  start_events: gaming_selected
  stop_events: gaming_complete, gaming_failed

light_player:
  mode_gaming_started:
    - show: gaming_mode_wave_red
      repeat: yes
  mode_gaming_stopping:
    - show: gaming_mode_wave_red
      action: stop

shot_profiles:
  gaming:
    states:
      - name: active
        light_script: flash_red
      - name: complete
        light_script: on_red

shots:
  drop_target_left_1:
    profile: gaming
    reset_events: mode_gaming_stopping
  drop_target_left_2:
    profile: gaming
    reset_events: mode_gaming_stopping
  drop_target_left_3:
    profile: gaming
    reset_events: mode_gaming_stopping
  kick_out_left:
    profile: gaming
    enable_events: drop_target_bank_left_down
    reset_events: mode_gaming_stopping
  kick_out_right:
    profile: gaming
    enable_events: drop_target_bank_left_down
    reset_events: mode_gaming_stopping

shot_groups:
  drop_target_bank_left:
    shots: drop_target_left_1, drop_target_left_2, drop_target_left_3

logic_blocks:
  sequences:
    gaming_stage_1:
      events:
        - drop_target_bank_left_down
      reset_events: mode_gaming_stopping
    gaming_stage_2:
      events:
        - logicblock_gaming_stage_1_complete
        - kick_out_left_gaming_active_hit, kick_out_right_gaming_active_hit
      reset_events: mode_gaming_stopping
    gaming:
      events:
        - logicblock_gaming_stage_2_complete
        - kick_out_left_gaming_active_hit, kick_out_right_gaming_active_hit
      enable_events: drop_target_bank_left_down
      reset_events: mode_gaming_stopping
      events_when_complete: gaming_complete, carousel_mode_complete

slide_player:
  gaming_selected:
    - type: text
      text: "GAMING BOTS!"
      expire: 3s
  gaming_stage_1:
    - type: text
      text: "ROLL THE DICE!"
      expire: 3s

scoring:
  logicblock_gaming_stage_1_complete:
    score: 10000

  logicblock_gaming_stage_2_complete:
    score: 20000

  gaming_complete:
    score: 120000
