# config_version=3

mode:
  priority: 100
  code: jackpot.jackpot
  start_events: jackpot_enabled
  stop_events: jackpot_complete, timer_jackpot_timer_complete

shot_profiles:
  jackpot:
    states:
      - name: active

shots:
  kick_out_right:
    profile: jackpot
    tags: jackpot_shot
    enable_events: enable_jackpot_mode_shot_kickout_right
    disable_events: disable_jackpot_mode_shot_kickout_right
    reset_events: disable_jackpot_mode_shot_kickout_right

light_player:
  mode_jackpot_started:
    - show: jackpot_chase_rainbow
      repeat: yes
  mode_jackpot_stopping:
    - show: jackpot_chase_rainbow
      action: stop
  enable_jackpot_mode_shot_kickout_right:
    - show: kick_out_right_arrow_chase_rainbow
      repeat: yes
  disable_jackpot_mode_shot_kickout_right:
    - show: kick_out_right_arrow_chase_rainbow
      action: stop

# logic_blocks:
#   sequences:
#     jackpot_sequence:
#       events:
#         - s_test_4_active
#       events_when_complete: jackpot_complete

timers:
  jackpot_timer:
    end_value: 5
    control_events:
      - event: mode_jackpot_stopping
        action: jump
        value: 0
    start_running: true
